# This starter workflow is for a CMake project running on multiple platforms. There is a different starter workflow if you just want a single platform.
# See: https://github.com/actions/starter-workflows/blob/main/ci/cmake-single-platform.yml
name: Build cross-platform binaries

on:
  push:
    branches:
      - cicd-build

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      # Set fail-fast to false to ensure that feedback is delivered for all matrix combinations. Consider changing this to true when your workflow is stable.
      fail-fast: false

      # Set up a matrix to run the following configurations:
      # 1. <Windows, Release, latest MSVC compiler toolchain on the default runner image, default generator>
      # 2. <Linux, Release, latest GCC compiler toolchain on the default runner image, default generator>
      matrix:
        os: [ubuntu-latest, windows-latest]
        include:
          - os: windows-latest
          - os: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: true

    - name: Set up CMake and Ninja
      uses: lukka/get-cmake@6b3e96a9bc9976b8b546346fdd102effedae0ca8

    - name: Set up MSVC toolchain
      if: runner.os == 'Windows'
      uses: ilammy/msvc-dev-cmd@0b201ec74fa43914dc39ae48a89fd1d8cb592756

    - name: Set reusable strings
      # Turn repeated input strings (such as the build output directory) into step outputs. These step outputs can be used throughout the workflow file.
      id: strings
      shell: bash
      run: |
        echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"

    - name: Configure CMake
      shell: bash
      run: |
        if [ "${{ matrix.os }}" = "windows-latest" ]; then
          cmake -B "${{ steps.strings.outputs.build-output-dir }}" \
            --preset default \
            -DCMAKE_BUILD_TYPE=Release \
            -DVCPKG_TARGET_TRIPLET=x64-windows-static-md \
            -DCMAKE_C_COMPILER=cl \
            -DCMAKE_CXX_COMPILER=cl \
            -S "${{ github.workspace }}"
        else
          cmake -B "${{ steps.strings.outputs.build-output-dir }}" \
            --preset default \
            -DCMAKE_BUILD_TYPE=Release \
            -DVCPKG_TARGET_TRIPLET=x64-linux \
            -S "${{ github.workspace }}"
        fi

    - name: Build
      run: cmake --build ${{ steps.strings.outputs.build-output-dir }} --config Release

    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: cimgui-${{ runner.os }}-${{ runner.arch }}
        path: ${{ steps.strings.outputs.build-output-dir }}/*${{ runner.os == 'Windows' && '.dll' || '.so' }}

  open-pr:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout Sovereign Engine code
      uses: actions/checkout@v4
      with:
        repository: opticfluorine/sovereign
        ref: main
        path: sovereign
        token: ${{ secrets.SOVEREIGN_GITHUB_PAT }}

    - name: Download build artifacts
      uses: actions/download-artifact@v4
      with:
        path: cimgui-artifacts

    - name: Unpack and place artifacts, commit changes
      run: |
        pushd $GITHUB_WORKSPACE/sovereign/src/Client/SovereignClient
        mkdir -p runtimes/linux-x64/native
        mkdir -p runtimes/win-x64/native
        cp -r $GITHUB_WORKSPACE/cimgui-artifacts/cimgui-Linux-X64/* runtimes/linux-x64/native/
        cp -r $GITHUB_WORKSPACE/cimgui-artifacts/cimgui-Windows-X64/* runtimes/win-x64/native/
        popd

    - name: Create pull request
      uses: peter-evans/create-pull-request@a59c52d55daab9f6a666e8741848b3cf101395a7
      with:
        token: ${{ secrets.SOVEREIGN_GITHUB_PAT }}
        path: sovereign
        commit-message: "Update cimgui binaries"
        title: "Update cimgui binaries"
        body: "Automated update of cimgui binaries from CI build."
        branch: update-cimgui-${{ github.run_id }}-${{ github.run_attempt }}
